spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mail?characterEncoding=utf8&useSSL=false
      username: root
      password: 1234
    rabbitmq:
      addresses: 127.0.0.1
      port: 5762
      username: guest
      password: guest

server:
  port: 8081

spring.redis.host: 127.0.0.1
spring.redis.port: 6379
#spring.redis.password
spring.redis.database: 1

